name: Run Pytest with Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.10']  # Add more Python versions as needed
      fail-fast: false  # Allow other jobs to run even if one fails

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov  # Install pytest-cov once

      - name: Run tests with coverage
        run: |
          pytest --cov=main --cov-report=xml --cov-report=html
        continue-on-error: true  # If tests fail, continue to upload reports

      - name: Upload coverage report
        if: success()  # Only upload if tests were successful
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml  # Or coverage.html if you prefer HTML format

      - name: Upload HTML coverage report
        if: success()  # Only upload if tests were successful
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage-report
          path: coverage/htmlcov/  # Path for HTML coverage report

